# Generated by Django 5.1.1 on 2024-09-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Details', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsDetails',
            new_name='Product',
        ),
    ]
